version: '3.8'
services:
  front_end:
    depends_on:
      - server
    build: ./front_end
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: exercise_frontend

    develop:
      watch:
        - path: ./front_end/package.json
          action: rebuild
        - path: ./front_end/package-lock.json
          action: rebuild
        - path: ./front_end
          target: /app
          action: sync
    networks:
      - exercise-network
  server:
    depends_on:
      - mongodb
    build: ./server
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
    container_name: exercise_server
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync
    networks:
      - exercise-network
  mongodb:
    image: mongo:latest
    container_name: exercise_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - gym_data:/data/db
    networks:
      - exercise-network

volumes:
  gym_data:
    driver: local

networks:
  exercise-network:
    driver: bridge

    